/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_csrf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Public customer self-registration. Creates a Django user, places it
         *     in the ``customer`` group, attaches a Customer profile (without a car
         *     yet — the user adds one from /my/cars right after), and logs the user
         *     in so the SPA can keep navigating without a second round-trip.
         */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/car-wash/availability/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["car_wash_availability_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/car-wash/bookings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["car_wash_bookings_retrieve"];
        put?: never;
        post: operations["car_wash_bookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/car-wash/bookings/{id}/cancel/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["car_wash_bookings_cancel_partial_update"];
        trace?: never;
    };
    "/api/car-wash/bookings/{id}/reschedule/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["car_wash_bookings_reschedule_partial_update"];
        trace?: never;
    };
    "/api/car-wash/bookings/{id}/status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["car_wash_bookings_status_partial_update"];
        trace?: never;
    };
    "/api/car-wash/wash-types/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["car_wash_wash_types_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cars/brands/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cars_brands_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cars/models/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cars_models_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cars/types/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cars_types_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/cars/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["customers_cars_retrieve"];
        put?: never;
        post: operations["customers_cars_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/cars/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["customers_cars_destroy"];
        options?: never;
        head?: never;
        patch: operations["customers_cars_partial_update"];
        trace?: never;
    };
    "/api/customers/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["customers_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manager/bookings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["manager_bookings_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manager/bookings/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["manager_booking_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manager/bookings/{id}/assign/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["manager_bookings_assign_partial_update"];
        trace?: never;
    };
    "/api/manager/bookings/{id}/audit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["manager_bookings_audit_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manager/bookings/{id}/status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["manager_bookings_status_partial_update"];
        trace?: never;
    };
    "/api/manager/reports/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Manager-facing aggregates for the daily and weekly reporting page.
         *
         *     Accepts ``?station=&date_from=&date_to=`` query params; ``date_from``
         *     defaults to today, ``date_to`` to ``date_from``. Filters bookings by
         *     ``starts_at`` (inclusive). Aggregates honour ``ManagerStationAccess``
         *     and only revenue from ``payment_status="paid"`` rows is counted; all
         *     booking counts use any non-cancelled status.
         */
        get: operations["manager_reports_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manager/resource-blocks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["manager_resource_blocks_retrieve"];
        put?: never;
        post: operations["manager_resource_blocks_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manager/schedule/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["manager_schedule_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/manager/shifts/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["manager_shifts_retrieve"];
        put?: never;
        post: operations["manager_shifts_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/personal/stations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["personal_stations_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_csrf_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    [key: string]: unknown;
                };
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    [key: string]: unknown;
                };
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    [key: string]: unknown;
                };
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    car_wash_availability_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    car_wash_bookings_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    car_wash_bookings_create: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    [key: string]: unknown;
                };
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    car_wash_bookings_cancel_partial_update: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    [key: string]: unknown;
                };
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    car_wash_bookings_reschedule_partial_update: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    [key: string]: unknown;
                };
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    car_wash_bookings_status_partial_update: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    [key: string]: unknown;
                };
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    car_wash_wash_types_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    cars_brands_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    cars_models_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    cars_types_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    customers_cars_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    customers_cars_create: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    [key: string]: unknown;
                };
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    customers_cars_destroy: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    customers_cars_partial_update: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    [key: string]: unknown;
                };
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    customers_me_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    manager_bookings_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    manager_booking_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    manager_bookings_assign_partial_update: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    [key: string]: unknown;
                };
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    manager_bookings_audit_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    manager_bookings_status_partial_update: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    [key: string]: unknown;
                };
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    manager_reports_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    manager_resource_blocks_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    manager_resource_blocks_create: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    [key: string]: unknown;
                };
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    manager_schedule_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    manager_shifts_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    manager_shifts_create: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/vnd.api+json": {
                    [key: string]: unknown;
                };
                "application/json": {
                    [key: string]: unknown;
                };
                "application/x-www-form-urlencoded": {
                    [key: string]: unknown;
                };
                "multipart/form-data": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    personal_stations_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "vnd.api+json";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                    "application/vnd.api+json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
