# Generated by Django 4.1.5 on 2023-01-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_wash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'verbose_name': 'Табель учета рабочего времени', 'verbose_name_plural': 'Учет рабочего времен'},
        ),
    ]
