# Generated by Django 4.1.5 on 2023-01-11 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_car_cartype'),
        ('cars', '0001_initial'),
        ('car_wash', '0002_alter_timesheet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='washcoast',
            options={'verbose_name': 'Стоимость мойки', 'verbose_name_plural': 'Стоимость мойки'},
        ),
        migrations.AlterModelOptions(
            name='washduration',
            options={'verbose_name': 'Время мойки', 'verbose_name_plural': 'Время мойки'},
        ),
        migrations.AlterField(
            model_name='washcoast',
            name='carType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cartype', verbose_name='Тип авто'),
        ),
        migrations.AlterField(
            model_name='washduration',
            name='carType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cartype', verbose_name='Тип авто'),
        ),
        migrations.DeleteModel(
            name='CarType',
        ),
    ]
