# Generated by Django 4.1.5 on 2023-01-11 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_schedule_washstation_alter_schedule_washer'),
        ('personal', '0001_initial'),
        ('car_wash', '0003_alter_washcoast_options_alter_washduration_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='dateType',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='washStation',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='washer',
        ),
        migrations.RemoveField(
            model_name='washstation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='washstation',
            name='district',
        ),
        migrations.AlterField(
            model_name='downpayment',
            name='washStation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.washstation', verbose_name='Станция мойки'),
        ),
        migrations.AlterField(
            model_name='washcoast',
            name='washStation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.washstation', verbose_name='Станция мойки'),
        ),
        migrations.AlterField(
            model_name='washduration',
            name='washStation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.washstation', verbose_name='Станция мойки'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='DateType',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='TimeSheet',
        ),
        migrations.DeleteModel(
            name='Washer',
        ),
        migrations.DeleteModel(
            name='WashStation',
        ),
    ]
