# Generated by Django 4.1.5 on 2026-05-06 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_alter_car_cartype"),
        ("personal", "0001_initial"),
        ("car_wash", "0004_remove_timesheet_datetype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_at", models.DateTimeField(verbose_name="Начало записи")),
                ("ends_at", models.DateTimeField(verbose_name="Окончание записи")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("pending", "Ожидает подтверждения"),
                            ("confirmed", "Подтверждена"),
                            ("in_progress", "В работе"),
                            ("completed", "Завершена"),
                            ("cancelled", "Отменена"),
                            ("no_show", "Клиент не приехал"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Стоимость"
                    ),
                ),
                (
                    "down_payment",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Предоплата"
                    ),
                ),
                (
                    "residual",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Остаток"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="customer.car",
                        verbose_name="Автомобиль",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="customer.customer",
                        verbose_name="Заказчик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на мойку",
                "verbose_name_plural": "Записи на мойку",
            },
        ),
        migrations.CreateModel(
            name="WasherShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_at", models.DateTimeField(verbose_name="Начало смены")),
                ("ends_at", models.DateTimeField(verbose_name="Окончание смены")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "wash_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="washer_shifts",
                        to="personal.washstation",
                        verbose_name="Станция мойки",
                    ),
                ),
                (
                    "washer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to="personal.washer",
                        verbose_name="Мойщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Смена мойщика",
                "verbose_name_plural": "Смены мойщиков",
            },
        ),
        migrations.CreateModel(
            name="WashBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "wash_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wash_boxes",
                        to="personal.washstation",
                        verbose_name="Станция мойки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бокс мойки",
                "verbose_name_plural": "Боксы мойки",
            },
        ),
        migrations.CreateModel(
            name="ResourceBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_at", models.DateTimeField(verbose_name="Начало блокировки")),
                ("ends_at", models.DateTimeField(verbose_name="Окончание блокировки")),
                ("reason", models.CharField(max_length=255, verbose_name="Причина")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "wash_box",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_blocks",
                        to="car_wash.washbox",
                        verbose_name="Бокс",
                    ),
                ),
                (
                    "wash_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_blocks",
                        to="personal.washstation",
                        verbose_name="Станция мойки",
                    ),
                ),
                (
                    "washer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resource_blocks",
                        to="personal.washer",
                        verbose_name="Мойщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блокировка ресурса",
                "verbose_name_plural": "Блокировки ресурсов",
            },
        ),
        migrations.CreateModel(
            name="BookingAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("main", "Основной"), ("assistant", "Помощник")],
                        default="main",
                        max_length=20,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="car_wash.booking",
                        verbose_name="Запись",
                    ),
                ),
                (
                    "washer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="booking_assignments",
                        to="personal.washer",
                        verbose_name="Мойщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение мойщика",
                "verbose_name_plural": "Назначения мойщиков",
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="wash_box",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="car_wash.washbox",
                verbose_name="Бокс",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="wash_station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="personal.washstation",
                verbose_name="Станция мойки",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="wash_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="car_wash.washtype",
                verbose_name="Тип мойки",
            ),
        ),
        migrations.AddIndex(
            model_name="washershift",
            index=models.Index(
                fields=["wash_station", "starts_at", "ends_at"],
                name="shift_station_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="washershift",
            index=models.Index(
                fields=["washer", "starts_at", "ends_at"], name="shift_washer_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="washershift",
            constraint=models.CheckConstraint(
                check=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="washer_shift_ends_after_start",
            ),
        ),
        migrations.AddIndex(
            model_name="washbox",
            index=models.Index(
                fields=["wash_station", "is_active"], name="wash_box_station_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="washbox",
            constraint=models.UniqueConstraint(
                fields=("wash_station", "name"), name="unique_wash_box_per_station"
            ),
        ),
        migrations.AddIndex(
            model_name="resourceblock",
            index=models.Index(
                fields=["wash_station", "starts_at", "ends_at"],
                name="block_station_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resourceblock",
            index=models.Index(
                fields=["wash_box", "starts_at", "ends_at"], name="block_box_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourceblock",
            index=models.Index(
                fields=["washer", "starts_at", "ends_at"], name="block_washer_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="resourceblock",
            constraint=models.CheckConstraint(
                check=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="resource_block_ends_after_start",
            ),
        ),
        migrations.AddIndex(
            model_name="bookingassignment",
            index=models.Index(fields=["washer"], name="assignment_washer_idx"),
        ),
        migrations.AddConstraint(
            model_name="bookingassignment",
            constraint=models.UniqueConstraint(
                fields=("booking", "washer"), name="unique_booking_washer_assignment"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["wash_station", "starts_at", "ends_at"],
                name="booking_station_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["wash_box", "starts_at", "ends_at"], name="booking_box_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["customer", "starts_at"], name="booking_customer_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="booking_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                check=models.Q(("ends_at__gt", models.F("starts_at"))),
                name="booking_ends_after_start",
            ),
        ),
    ]
