# Generated by Django 4.1.5 on 2026-05-06 14:20

from django.db import migrations


ROLE_GROUPS = ("customer", "manager", "admin")


def create_role_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")

    for group_name in ROLE_GROUPS:
        Group.objects.get_or_create(name=group_name)


def remove_role_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=ROLE_GROUPS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("car_wash", "0005_booking_washershift_washbox_resourceblock_and_more"),
    ]

    operations = [
        migrations.RunPython(create_role_groups, remove_role_groups),
    ]
