# Generated by Django 4.1.5 on 2026-05-07 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def grant_existing_managers_all_stations(apps, schema_editor):
    group_model = apps.get_model("auth", "Group")
    auth_app, auth_model = settings.AUTH_USER_MODEL.split(".")
    user_model = apps.get_model(auth_app, auth_model)
    station_model = apps.get_model("personal", "WashStation")
    access_model = apps.get_model("car_wash", "ManagerStationAccess")

    manager_group = group_model.objects.filter(name="manager").first()
    if manager_group is None:
        return

    manager_ids = user_model.objects.filter(groups=manager_group).values_list(
        "id",
        flat=True,
    )
    station_ids = station_model.objects.values_list("id", flat=True)

    for user_id in manager_ids:
        for station_id in station_ids:
            access_model.objects.get_or_create(
                user_id=user_id,
                wash_station_id=station_id,
                defaults={"is_active": True},
            )


class Migration(migrations.Migration):

    dependencies = [
        ("personal", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("car_wash", "0007_rename_washcoast_washcost"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagerStationAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_wash_station_access",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "wash_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_access",
                        to="personal.washstation",
                        verbose_name="Станция мойки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Доступ руководителя к станции",
                "verbose_name_plural": "Доступы руководителей к станциям",
            },
        ),
        migrations.RunPython(
            grant_existing_managers_all_stations,
            migrations.RunPython.noop,
        ),
        migrations.AddIndex(
            model_name="managerstationaccess",
            index=models.Index(
                fields=["user", "is_active"], name="mgr_station_user_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="managerstationaccess",
            constraint=models.UniqueConstraint(
                fields=("user", "wash_station"), name="unique_manager_station_access"
            ),
        ),
    ]
