# Generated by Django 4.1.5 on 2026-05-08 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("car_wash", "0008_managerstationaccess_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("booking_created", "Запись создана"),
                            ("booking_cancelled", "Запись отменена"),
                            ("booking_rescheduled", "Запись перенесена"),
                            ("booking_status_changed", "Статус изменён"),
                            ("booking_assigned", "Назначение обновлено"),
                            ("shift_created", "Смена создана"),
                            ("resource_block_created", "Блокировка создана"),
                        ],
                        max_length=40,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(max_length=40, verbose_name="Тип сущности"),
                ),
                ("entity_id", models.PositiveIntegerField(verbose_name="ID сущности")),
                (
                    "context",
                    models.JSONField(blank=True, default=dict, verbose_name="Контекст"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Время"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="car_wash_audit_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Аудит-событие",
                "verbose_name_plural": "Аудит-события",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["entity_type", "entity_id", "created_at"],
                name="audit_entity_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditevent",
            index=models.Index(
                fields=["actor", "created_at"], name="audit_actor_time_idx"
            ),
        ),
    ]
