# Generated by Django 4.1.5 on 2026-05-08 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("car_wash", "0009_auditevent_auditevent_audit_entity_time_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("booking_created", "Запись создана"),
                            ("booking_rescheduled", "Запись перенесена"),
                            ("booking_cancelled", "Запись отменена"),
                            ("booking_status_changed", "Статус изменён"),
                        ],
                        max_length=40,
                        verbose_name="Событие",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "В очереди"),
                            ("sent", "Отправлено"),
                            ("failed", "Ошибка"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Полезная нагрузка"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="Последняя ошибка"),
                ),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Попыток"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отправлено"
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_events",
                        to="car_wash.booking",
                        verbose_name="Запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление в outbox",
                "verbose_name_plural": "Уведомления в outbox",
                "ordering": ("created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="notificationoutbox",
            index=models.Index(
                fields=["status", "created_at"], name="outbox_status_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationoutbox",
            index=models.Index(
                fields=["booking", "event"], name="outbox_booking_event_idx"
            ),
        ),
    ]
