# Generated by Django 4.1.5 on 2026-05-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_wash", "0010_notificationoutbox_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Оплачено"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_provider",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Провайдер оплаты"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_reference",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Не оплачено"),
                    ("awaiting", "Ожидает оплаты"),
                    ("paid", "Оплачено"),
                    ("refunded", "Возврат"),
                ],
                default="unpaid",
                max_length=20,
                verbose_name="Статус оплаты",
            ),
        ),
    ]
