# Generated by Django 4.1.5 on 2023-01-11 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('car_wash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBegin', models.DateTimeField(verbose_name='Время начала')),
                ('dateEnd', models.DateTimeField(verbose_name='Время окончания')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость')),
                ('downPayment', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Предоплата')),
                ('residual', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Остаток')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer', verbose_name='Заказчик')),
                ('washStation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_wash.washstation', verbose_name='Станция мойки')),
                ('washer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_wash.washer', verbose_name='Мойщик')),
            ],
            options={
                'verbose_name': 'Расписание работы',
            },
        ),
    ]
