# Generated by Django 4.1.5 on 2023-01-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_schedule_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание'},
        ),
    ]
