# Generated by Django 4.1.5 on 2026-05-07 07:01

from django.db import migrations, models
import django.db.models.deletion


def link_legacy_customer_cars(apps, schema_editor):
    customer_model = apps.get_model("customer", "Customer")
    car_model = apps.get_model("customer", "Car")

    for customer in customer_model.objects.exclude(car_id__isnull=True):
        car_model.objects.filter(
            id=customer.car_id,
            customer__isnull=True,
        ).update(customer_id=customer.id)


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cars",
                to="customer.customer",
                verbose_name="Заказчик",
            ),
        ),
        migrations.RunPython(link_legacy_customer_cars, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="customer",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="legacy_customers",
                to="customer.car",
                verbose_name="Автомобиль",
            ),
        ),
    ]
