# Generated by Django 4.1.5 on 2026-05-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_car_customer_alter_customer_car"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
    ]
