# Generated by Django 4.1.5 on 2026-05-08 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_car_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_customers",
                to="customer.car",
                verbose_name="Автомобиль",
            ),
        ),
    ]
