# Generated by Django 5.2 on 2026-05-12

from django.db import migrations
from django.db.models import Count


def assert_unique_phone_numbers(apps, schema_editor):
    Customer = apps.get_model("customer", "Customer")
    if Customer.objects.filter(phoneNumber__isnull=True).exists():
        raise RuntimeError(
            "Cannot add a unique constraint to customer.Customer.phoneNumber "
            "while NULL phone numbers exist."
        )

    duplicates = (
        Customer.objects.values("phoneNumber")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
        .order_by("phoneNumber")
    )

    if duplicates.exists():
        duplicate_values = ", ".join(
            f"{entry['phoneNumber']!r} ({entry['total']})"
            for entry in duplicates[:10]
        )
        raise RuntimeError(
            "Cannot add a unique constraint to customer.Customer.phoneNumber "
            f"while duplicate values exist: {duplicate_values}."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_alter_customer_car"),
    ]

    operations = [
        migrations.RunPython(
            assert_unique_phone_numbers,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
