# Generated by Django 5.2 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0007_assert_unique_customer_phone_numbers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phoneNumber",
            field=models.CharField(
                max_length=100,
                null=False,
                unique=True,
                verbose_name="Номер телефона",
            ),
        ),
    ]
