# Generated by Django 4.1.5 on 2023-01-11 12:36

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='DateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('duration', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='Длительность дня, часов')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип дня',
                'verbose_name_plural': 'Типы дня',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='Washer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('surname', models.CharField(max_length=150, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Мойщик',
                'verbose_name_plural': 'Мойщики',
            },
        ),
        migrations.CreateModel(
            name='WashStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.city', verbose_name='Город')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.district', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Станция мойки',
                'verbose_name_plural': 'Станции мойки',
            },
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateBegin', models.DateField(default=datetime.date.today, verbose_name='Дата начала')),
                ('dateEnd', models.DateField(default=datetime.date.today, verbose_name='Дата окончания')),
                ('dateType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.datetype', verbose_name='тип дня')),
                ('washStation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.washstation', verbose_name='Станция мойки')),
                ('washer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.washer', verbose_name='Мойщик')),
            ],
            options={
                'verbose_name': 'Табель учета рабочего времени',
                'verbose_name_plural': 'Учет рабочего времен',
            },
        ),
    ]
